### PR TITLE
Add {oBERO} token

### PR DESCRIPTION
**Pull request by berabuilder**
## PR-Codex overview
The focus of this PR is to add a new token `oBERO` with chainId 80084 and address 0x7629668774f918c00Eb4b03AdF5C4e2E53d45f0b.

### Detailed summary
- Added a new token `oBERO` to the token list
- Token has symbol, name, decimals, and logoURI specified
- Token belongs to chainId 80084 with address 0x7629668774f918c00Eb4b03AdF5C4e2E53d45f0b

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by xsubject — CHANGES_REQUESTED** [review]
I think you missed adding a comma. Make sure the JSON is valid

**Comment by berabuilder** [comment]
@xsubject added comma

**Comment by xsubject** [comment]
Your file name must be in lower case, identical to the name from the link

**Comment by berabuilder** [comment]
done ser

**Pull request merged**
